<?php require_once 'includes/cabecera.php';?>
<?php require_once 'includes/barralateralderecha.php';?>
        <!-- ********************CAJA PRINCIPAL******************** -->
        <div id="contenedorprincipal">
            <h1>ÚLTIMAS ENTRADAS</h1>
            <article class="entrada">
                <a href="">
                    <h2>TÍTULO DE ENTRADA</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed facilisis, odio in mollis iaculis, sapien eros tincidunt arcu, sit amet sagittis odio magna ornare velit. Quisque dapibus enim lacus, vel ullamcorper augue malesuada vitae. Nunc est orci, molestie in lectus pretium, finibus scelerisque tortor. Donec libero nisl, pulvinar et elit in, aliquam porta urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque non mauris sapien. Duis consectetur suscipit dolor, condimentum pretium orci sagittis ut. Aliquam eu condimentum ipsum. Etiam vel lacus eu purus tristique feugiat.
                        Quisque vehicula accumsan neque, in dapibus augue venenatis et. Suspendisse rhoncus augue eget sapien venenatis, et vehicula elit tempor. Sed mi orci, viverra et malesuada non, consectetur in ex. Praesent sit amet turpis volutpat diam consectetur pellentesque. Nam sit amet nulla rhoncus, condimentum urna a, sagittis purus. Sed venenatis odio consequat mi pulvinar, id egestas magna blandit. Nullam rhoncus hendrerit sem. In sagittis sed nisi non finibus. Proin interdum justo eget sollicitudin vulputate. Suspendisse mi nulla, vestibulum eget dui at, maximus euismod dui. Nullam porttitor, velit vel imperdiet euismod, erat nisl vestibulum neque, eu porttitor felis libero eget est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eleifend quam metus, ut elementum purus commodo non. Nunc vitae pulvinar nisl.
                        Donec suscipit, metus eget ornare blandit, odio augue molestie augue, ac sollicitudin felis lorem eu lectus. Sed vehicula ac mi vitae eleifend. Integer odio arcu, ultrices sagittis placerat et, bibendum sit amet massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent dui orci, tempus id fringilla efficitur, aliquam in odio. Maecenas scelerisque vitae neque eget vestibulum. Cras eu vulputate sem. Nullam diam elit, blandit quis nibh quis, semper lobortis justo.
                        Sed convallis venenatis nibh vitae pharetra. Fusce bibendum, elit quis mollis faucibus, mauris metus pellentesque nisl, at imperdiet sem diam sed turpis. Vivamus tristique laoreet leo eu maximus. Morbi convallis ex ac sagittis facilisis. Nulla ac volutpat sapien. Donec tincidunt blandit est a facilisis. Praesent suscipit tempus erat, in facilisis lacus imperdiet a. Quisque fermentum sagittis nisi, id maximus diam luctus eget. Aliquam vitae nisi non odio pellentesque condimentum nec quis est. Mauris neque erat, pharetra vel hendrerit at, suscipit eget purus.
                        Aliquam nec pulvinar lectus, ut fringilla velit. Fusce tincidunt, est id egestas dapibus, risus eros semper urna, commodo ultrices augue ipsum id ligula. Sed id rutrum mi. Duis eu magna venenatis, pretium dui id, lobortis urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla venenatis cursus ligula vel porta. Cras laoreet egestas nulla vel pulvinar. Nulla facilisi. Morbi sed faucibus nulla. Pellentesque vitae bibendum quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent id turpis elementum lorem consectetur efficitur vitae at nunc. Phasellus risus mauris, feugiat non purus ac, tincidunt mattis ex.
                    </p>
                </a>
            </article>
            <article class="entrada">
                <a href="">
                    <h2>TÍTULO DE ENTRADA</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed facilisis, odio in mollis iaculis, sapien eros tincidunt arcu, sit amet sagittis odio magna ornare velit. Quisque dapibus enim lacus, vel ullamcorper augue malesuada vitae. Nunc est orci, molestie in lectus pretium, finibus scelerisque tortor. Donec libero nisl, pulvinar et elit in, aliquam porta urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque non mauris sapien. Duis consectetur suscipit dolor, condimentum pretium orci sagittis ut. Aliquam eu condimentum ipsum. Etiam vel lacus eu purus tristique feugiat.
                        Quisque vehicula accumsan neque, in dapibus augue venenatis et. Suspendisse rhoncus augue eget sapien venenatis, et vehicula elit tempor. Sed mi orci, viverra et malesuada non, consectetur in ex. Praesent sit amet turpis volutpat diam consectetur pellentesque. Nam sit amet nulla rhoncus, condimentum urna a, sagittis purus. Sed venenatis odio consequat mi pulvinar, id egestas magna blandit. Nullam rhoncus hendrerit sem. In sagittis sed nisi non finibus. Proin interdum justo eget sollicitudin vulputate. Suspendisse mi nulla, vestibulum eget dui at, maximus euismod dui. Nullam porttitor, velit vel imperdiet euismod, erat nisl vestibulum neque, eu porttitor felis libero eget est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eleifend quam metus, ut elementum purus commodo non. Nunc vitae pulvinar nisl.
                        Donec suscipit, metus eget ornare blandit, odio augue molestie augue, ac sollicitudin felis lorem eu lectus. Sed vehicula ac mi vitae eleifend. Integer odio arcu, ultrices sagittis placerat et, bibendum sit amet massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent dui orci, tempus id fringilla efficitur, aliquam in odio. Maecenas scelerisque vitae neque eget vestibulum. Cras eu vulputate sem. Nullam diam elit, blandit quis nibh quis, semper lobortis justo.
                        Sed convallis venenatis nibh vitae pharetra. Fusce bibendum, elit quis mollis faucibus, mauris metus pellentesque nisl, at imperdiet sem diam sed turpis. Vivamus tristique laoreet leo eu maximus. Morbi convallis ex ac sagittis facilisis. Nulla ac volutpat sapien. Donec tincidunt blandit est a facilisis. Praesent suscipit tempus erat, in facilisis lacus imperdiet a. Quisque fermentum sagittis nisi, id maximus diam luctus eget. Aliquam vitae nisi non odio pellentesque condimentum nec quis est. Mauris neque erat, pharetra vel hendrerit at, suscipit eget purus.
                        Aliquam nec pulvinar lectus, ut fringilla velit. Fusce tincidunt, est id egestas dapibus, risus eros semper urna, commodo ultrices augue ipsum id ligula. Sed id rutrum mi. Duis eu magna venenatis, pretium dui id, lobortis urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla venenatis cursus ligula vel porta. Cras laoreet egestas nulla vel pulvinar. Nulla facilisi. Morbi sed faucibus nulla. Pellentesque vitae bibendum quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent id turpis elementum lorem consectetur efficitur vitae at nunc. Phasellus risus mauris, feugiat non purus ac, tincidunt mattis ex.
                    </p>
                </a>
            </article>
            <article class="entrada">
                <a href="">
                    <h2>TÍTULO DE ENTRADA</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed facilisis, odio in mollis iaculis, sapien eros tincidunt arcu, sit amet sagittis odio magna ornare velit. Quisque dapibus enim lacus, vel ullamcorper augue malesuada vitae. Nunc est orci, molestie in lectus pretium, finibus scelerisque tortor. Donec libero nisl, pulvinar et elit in, aliquam porta urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque non mauris sapien. Duis consectetur suscipit dolor, condimentum pretium orci sagittis ut. Aliquam eu condimentum ipsum. Etiam vel lacus eu purus tristique feugiat.
                        Quisque vehicula accumsan neque, in dapibus augue venenatis et. Suspendisse rhoncus augue eget sapien venenatis, et vehicula elit tempor. Sed mi orci, viverra et malesuada non, consectetur in ex. Praesent sit amet turpis volutpat diam consectetur pellentesque. Nam sit amet nulla rhoncus, condimentum urna a, sagittis purus. Sed venenatis odio consequat mi pulvinar, id egestas magna blandit. Nullam rhoncus hendrerit sem. In sagittis sed nisi non finibus. Proin interdum justo eget sollicitudin vulputate. Suspendisse mi nulla, vestibulum eget dui at, maximus euismod dui. Nullam porttitor, velit vel imperdiet euismod, erat nisl vestibulum neque, eu porttitor felis libero eget est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eleifend quam metus, ut elementum purus commodo non. Nunc vitae pulvinar nisl.
                        Donec suscipit, metus eget ornare blandit, odio augue molestie augue, ac sollicitudin felis lorem eu lectus. Sed vehicula ac mi vitae eleifend. Integer odio arcu, ultrices sagittis placerat et, bibendum sit amet massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent dui orci, tempus id fringilla efficitur, aliquam in odio. Maecenas scelerisque vitae neque eget vestibulum. Cras eu vulputate sem. Nullam diam elit, blandit quis nibh quis, semper lobortis justo.
                        Sed convallis venenatis nibh vitae pharetra. Fusce bibendum, elit quis mollis faucibus, mauris metus pellentesque nisl, at imperdiet sem diam sed turpis. Vivamus tristique laoreet leo eu maximus. Morbi convallis ex ac sagittis facilisis. Nulla ac volutpat sapien. Donec tincidunt blandit est a facilisis. Praesent suscipit tempus erat, in facilisis lacus imperdiet a. Quisque fermentum sagittis nisi, id maximus diam luctus eget. Aliquam vitae nisi non odio pellentesque condimentum nec quis est. Mauris neque erat, pharetra vel hendrerit at, suscipit eget purus.
                        Aliquam nec pulvinar lectus, ut fringilla velit. Fusce tincidunt, est id egestas dapibus, risus eros semper urna, commodo ultrices augue ipsum id ligula. Sed id rutrum mi. Duis eu magna venenatis, pretium dui id, lobortis urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla venenatis cursus ligula vel porta. Cras laoreet egestas nulla vel pulvinar. Nulla facilisi. Morbi sed faucibus nulla. Pellentesque vitae bibendum quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent id turpis elementum lorem consectetur efficitur vitae at nunc. Phasellus risus mauris, feugiat non purus ac, tincidunt mattis ex.
                    </p>
                </a>
            </article>
            
            <div id="ver-todas">
            <a href=""> - MOSTRAR TODAS LAS ENTRADAS - </a>
            </div>
        </div>

<?php require_once 'includes/pie.php';?>
<!-- http://localhost/master-tutorial/proyecto-php/index.php -->